export const videos = [
    {
        id: 1,
        title: "Understanding Anxiety Disorders",
        username: "mentalHealthGuru",
        videoUrl: "#",
        avatar: "https://source.unsplash.com/random/400x400?portrait",
        image: "https://picsum.photos/200/300?random",
        description:
            "Dive deep into the world of anxiety disorders with our expert breakdown. This video discusses causes, symptoms, and effective treatments for anxiety, helping viewers identify and manage these conditions with confidence.",
        category: "Anxiety",
        tags: ["anxiety", "mental health", "stress management"],
        datePublished: "2024-08-26",
        author: "Dr. John Doe",
        views: 1200,
        watchTime: "5 min",
        ageGroup: "Adult",
        gender: "All",
    },
    {
        id: 2,
        title: "Managing Social Anxiety",
        username: "mindfulTherapist",
        videoUrl: "#",
        avatar: "https://source.unsplash.com/random/400x400?portrait",
        image: "https://picsum.photos/200/300?random=2",
        description:
            "Explore practical strategies for managing social anxiety in this comprehensive guide. From behavioral techniques to lifestyle adjustments, learn how to navigate social situations more comfortably and effectively.",
        category: "Social Welfare",
        tags: ["social anxiety", "anxiety", "mental health", "Social Welfare"],
        datePublished: "2024-09-01",
        author: "Dr. Jane Smith",
        views: 950,
        watchTime: "8 min",
        ageGroup: "Adult",
        gender: "All",
    },
    {
        id: 3,
        title: "Introduction to Mindfulness",
        username: "zenMaster",
        videoUrl: "#",
        avatar: "https://source.unsplash.com/random/400x400?portrait",
        image: "https://picsum.photos/200/300?random=3",
        description:
            "Begin your mindfulness journey with this introductory video. Discover the core principles of mindfulness and how simple daily practices can significantly reduce stress and increase overall happiness.",
        category: "Mindfulness",
        tags: ["mindfulness", "meditation", "mental wellness"],
        datePublished: "2024-09-03",
        author: "Master Zen",
        views: 3200,
        watchTime: "12 min",
        ageGroup: "All",
        gender: "All",
    },
    {
        id: 4,
        title: "Coping with Depression",
        username: "mentalHealthAdvocate",
        videoUrl: "#",
        avatar: "https://source.unsplash.com/random/400x400?portrait",
        image: "https://picsum.photos/200/300?random=4",
        description:
            "Unpack the complexities of depression in this insightful video. Learn about the latest treatments, hear from experts on coping mechanisms, and discover supportive resources that can make a difference.",
        category: "Depression",
        tags: ["depression", "mental health", "coping strategies"],
        datePublished: "2024-08-20",
        author: "Dr. Robert Green",
        views: 1800,
        watchTime: "7 min",
        ageGroup: "Adult",
        gender: "All",
    },
    {
        id: 5,
        title: "The Power of Self-Care",
        username: "selfCareCoach",
        videoUrl: "#",
        avatar: "https://source.unsplash.com/random/400x400?portrait",
        image: "https://picsum.photos/200/300?random=5",
        description:
            "Join Coach Sarah Brown as she guides you through transformative self-care practices. Discover how prioritizing your well-being can lead to better health, increased productivity, and a happier life.",
        category: "Self-Care",
        tags: ["self-care", "mental wellness", "mindfulness"],
        datePublished: "2024-09-05",
        author: "Coach Sarah Brown",
        views: 2500,
        watchTime: "10 min",
        ageGroup: "All",
        gender: "All",
    },
    {
        id: 6,
        title: "Building Mental Resilience",
        username: "resilienceExpert",
        videoUrl: "#",
        avatar: "https://source.unsplash.com/random/400x400?portrait",
        image: "https://picsum.photos/200/300?random=6",
        description:
            "Learn how to build mental resilience from Dr. Emily Parker. This video provides actionable tips on staying strong in the face of adversity and bouncing back from challenges more robustly.",
        category: "Resilience",
        tags: ["resilience", "mental strength", "stress management"],
        datePublished: "2024-08-30",
        author: "Dr. Emily Parker",
        views: 2100,
        watchTime: "6 min",
        ageGroup: "All",
        gender: "All",
    },
    {
        id: 7,
        title: "Overcoming Stress with Meditation",
        username: "calmMind",
        videoUrl: "#",
        avatar: "https://source.unsplash.com/random/400x400?portrait",
        image: "https://picsum.photos/200/300?random=7",
        description:
            "Yogi Daniel takes you through various meditation techniques to combat stress effectively. Learn to focus, relax, and reclaim your mental peace through guided sessions designed for all skill levels.",
        category: "Stress Management",
        tags: ["stress", "meditation", "mental wellness"],
        datePublished: "2024-08-15",
        author: "Yogi Daniel",
        views: 3200,
        watchTime: "15 min",
        ageGroup: "All",
        gender: "All",
    }
];
